[keys]
secret = "asdf"

[http]
listen_address = "0.0.0.0:6200"

[cratedb]
url = "http://localhost:4200"
bulk_size = 1000
create_statement = "create table if not exists sensor(ts timestamp, data object, meta object, month as date_trunc('month', ts)) partitioned by (month)" # the create table statement. use your own ;)
insert_statement = "insert into sensor(ts, data, meta) values(?,?,?)" # the insert statement. should match the table schema ...

[[acls]]
name = "Raspberry 1"
roles = ["sensor"]
